#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
system description: a two-body floating system is considered. A magnetic force generated by a current
is applied to a iron ball, which is located directly under the magnet. A CuZn ball below is attached
to that iron ball by a spring with the spring constant kf.

problem specification for control problem: design of a full state feedback controller to control
position of the both balls.
"""
import numpy as np
import sympy as sp
from ackrep_core import ResultContainer

j = 1j  # imaginary unit


class ProblemSpecification(object):
    # system symbols for setting up the equation of motion
    p1, p2, pdot1, pdot2 = sp.symbols("p1, p2, pdot1, pdot2")
    xx = sp.Matrix([p1, p2, pdot1, pdot2])  # states of system
    i = sp.Symbol("i")
    u = [i]  # input of system

    # equilibrium points for linearization of the nonlinear system
    eqrt = [(p1, 0.01), (p2, 0.049), (pdot1, 0), (pdot2, 0), (i, 5)]
    xx0 = np.array([0.02, 0.05, 0, 0])  # initial condition
    tt = np.linspace(0, 10, 1000)  # vector for the time axis for simulating
    yr = 0  # reference output

    # desired poles of closed system
    poles_cl = [-60, -40, -1 + 16 * j, -1 - 16 * j]

    # plotting parameters
    titles_state = ['x1', 'x2', 'x1_dot', 'x2_dot']
    titles_output = ['y']
    x_label = 'time [s]'
    y_label_state = ['position [m]', 'position [m]', 'velocity [m/s]', 'velocity [m/s]']
    y_label_output = ['position [m]']
    graph_color = 'r'
    row_number = 2  # the number of images in each row

    @staticmethod
    def rhs(xx, uu):
        """ Right hand side of the equation of motion in nonlinear state space form
        :param xx:   system states x1: position of Fe-ball, x2: position of CuZn-ball
        :param uu:   system input
        :return:     nonlinear state space
        """
        m1 = 0.05  # mass of the iron ball in kg
        m2 = 0.04  # mass of the brass ball in kg
        kf = 10  # Spring constant in N/m
        g = 9.8  # acceleration of gravity in m/s^2
        k1 = 4e-5  # geometry constant
        k2 = 0.005  # air gap of magnet in m

        x1, x2, x3, x4 = xx
        u = uu

        p1_dot = (g * m1 - u[0] * k1 / (k2 + x1) ** 2 - kf * (x1 - x2)) / m1
        p2_dot = (g * m2 + kf * (x1 - x2)) / m2

        ff = sp.Matrix([x3,
                        x4,
                        p1_dot,
                        p2_dot])

        return ff

    @staticmethod
    def output_func(xx, uu):
        """ output equation of the system
        :param xx:   system states
        :param uu:   system input (not used in this case)
        :return:     output equation y = x1
        """
        x1, x2, x3, x4 = xx
        u = uu

        return sp.Matrix([x1])


def evaluate_solution(solution_data):
    """
    Condition: the both balls return to their original position at least after 4 seconds.
    :param solution_data: solution data of problem of solution
    :return:
    """
    P = ProblemSpecification
    success = all(abs(solution_data.res[800:, 0] - [P.eqrt[0][1]] * 200) < 1e-2) and \
              all(abs(solution_data.res[800:, 1] - [P.eqrt[1][1]] * 200) < 1e-2)

    return ResultContainer(success=success, score=1.0)
