# This file was autogenerated from the template: parameters.py.template (2022-10-10 15:53:28).

import sys
import os
import numpy as np
import sympy as sp

import tabulate as tab


#link to documentation with examples: https://ackrep-doc.readthedocs.io/en/latest/devdoc/contributing_data.html


# set model name
model_name = 'Decentralized Interconnected System'


# ---------- create symbolic parameters
A = sp.MatrixSymbol('A', 8, 8)
B = sp.MatrixSymbol('B', 8, 4)
B1 = sp.MatrixSymbol('B1', 8, 1)
C1 = sp.MatrixSymbol('C1', 8, 8)
C = sp.MatrixSymbol('C', 4, 8)
D11 = sp.MatrixSymbol('D11', 8, 1)
D12 = sp.MatrixSymbol('D12', 8, 4)
D21 = sp.MatrixSymbol('D21', 4, 1)

pp_symb = [A, B, B1, C1, C, D11, D12, D21]


# ---------- create auxiliary symbolic parameters 

# set numerical values of auxiliary parameters
# trailing "_nv" stands for "numerical value"
A_nv = sp.Matrix(np.array([[ 0.144 , -0.058 ,  0.056 ,  0.042 ,  0.12  ,  2.1454,  0.    ,
         0.08  ],
       [-0.506 , -0.236 , -0.02  , -0.012 , -0.06  , -0.909 ,  1.093 ,
        -0.04  ],
       [ 0.    ,  0.    , -0.278 ,  0.291 ,  0.    ,  0.    ,  0.    ,
         0.58  ],
       [ 0.    ,  0.    ,  0.    , -0.33  ,  0.    ,  0.    ,  0.    ,
         0.    ],
       [ 0.    ,  0.    ,  0.303 ,  0.029 , -1.67  ,  0.    ,  0.    ,
         0.092 ],
       [-0.154 ,  0.133 , -0.006 , -0.004 , -0.014 , -1.688 ,  0.236 ,
         0.013 ],
       [-0.345 ,  0.304 , -0.018 , -0.014 , -0.032 , -0.611 , -1.824 ,
        -0.024 ],
       [ 0.    ,  0.    ,  0.    ,  0.247 ,  0.    ,  0.    ,  0.    ,
        -1.978 ]]))
B_nv = sp.Matrix(np.array([[-0.076,  0.02 ,  0.   ,  0.   ],
       [ 0.588, -0.006,  0.   ,  0.   ],
       [ 0.   ,  0.152,  0.   ,  0.   ],
       [ 0.   ,  1.45 ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.012],
       [ 0.   ,  0.   ,  0.162, -0.002],
       [ 0.   ,  0.   ,  0.414, -0.008],
       [ 0.   ,  0.   ,  0.   ,  0.248]]))
B1_nv = sp.Matrix(np.array([[-0.076,  0.02 ,  0.   ,  0.   ],
       [ 0.588, -0.006,  0.   ,  0.   ],
       [ 0.   ,  0.152,  0.   ,  0.   ],
       [ 0.   ,  1.45 ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.012],
       [ 0.   ,  0.   ,  0.162, -0.002],
       [ 0.   ,  0.   ,  0.414, -0.008],
       [ 0.   ,  0.   ,  0.   ,  0.248]]))
C1_nv = sp.Matrix(np.array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]]))
C_nv = sp.Matrix(np.array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]]))
D11_nv = sp.Matrix(np.array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]]))
D12_nv = sp.Matrix(np.array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))
D21_nv = sp.Matrix(np.array([[0.],
       [0.],
       [0.],
       [0.]]))


# ---------- create symbolic parameter functions
# parameter values can be constant/fixed values OR set in relation to other parameters (for example: a = 2*b)  


# list of symbolic parameter functions
# tailing "_sf" stands for "symbolic parameter function"
pp_sf = [A_nv, B_nv, B1_nv, C1_nv, C_nv, D11_nv, D12_nv, D21_nv]


#  ---------- list for substitution
# -- entries are tuples like: (independent symbolic parameter, numerical value)
pp_subs_list = []


# OPTONAL: Dictionary which defines how certain variables shall be written
# in the table - key: Symbolic Variable, Value: LaTeX Representation/Code
# useful for example for complex variables: {Z: r"\underline{Z}"}
latex_names = {}


# ---------- Define LaTeX table

# Define table header 
# DON'T CHANGE FOLLOWING ENTRIES: "Symbol", "Value"
tabular_header = ["Symbol", "Value"]

# Define column text alignments
col_alignment = ["center", "left"]


# Define Entries of all columns before the Symbol-Column
# --- Entries need to be latex code
col_1 = [] 

# contains all lists of the columns before the "Symbol" Column
# --- Empty list, if there are no columns before the "Symbol" Column
start_columns_list = []


# Define Entries of the columns after the Value-Column
# --- Entries need to be latex code
col_4 = []

# contains all lists of columns after the FIX ENTRIES
# --- Empty list, if there are no columns after the "Value" column
end_columns_list = []