# This file was autogenerated from the template: simulation.py.template (2022-10-10 15:58:17).

import numpy as np
import system_model
from scipy.integrate import solve_ivp, odeint

from ackrep_core import ResultContainer
from ackrep_core.system_model_management import save_plot_in_dir
import matplotlib.pyplot as plt
import os
from ipydex import Container

# link to documentation with examples: https://ackrep-doc.readthedocs.io/en/latest/devdoc/contributing_data.html


def simulate():
    """
    simulate the system model with scipy.integrate.solve_ivp

    :return: result of solve_ivp, might contains input function
    """

    model = system_model.Model()

    rhs_xx_pp_symb = model.get_rhs_symbolic()
    rhs = model.get_rhs_func()

    # initial state values
    xx0 = np.ones(model.sys_dim)

    t_end = 10
    tt = np.linspace(0, t_end, 1000)

    simulation_data = solve_ivp(rhs, (0, t_end), xx0, t_eval=tt)

    # using odeint for models with large state vectors
    # res = odeint(rhs, y0=xx0, t=tt, tfirst=True)
    # simulation_data = Container()
    # simulation_data.y = res.transpose()
    # simulation_data.t = tt

    # postprocessing: calc output
    ny = 1
    C = model.get_parameter_value("C")
    D21 = model.get_parameter_value("D21")
    output = np.zeros((ny, len(tt)))
    for i in range(len(tt)):
        output[:,i] = np.matmul(C, simulation_data.y[:,i]) # + np.matmul(D21, w)
    simulation_data.output = output

    save_plot(simulation_data)

    return simulation_data


def save_plot(simulation_data):
    """
    plot your data and save the plot
    access to data via: simulation_data.t   array of time values
                        simulation_data.y   array of data components
                        simulation_data.uu  array of input values

    :param simulation_data: simulation_data of system_model
    :return: None
    """

    for i in range(simulation_data.output.shape[0]):
        plt.plot(simulation_data.t, simulation_data.output[i], label=f"$y_{i}$")

    plt.legend()
    plt.tight_layout()

    save_plot_in_dir()


def evaluate_simulation(simulation_data):
    """
    assert that the simulation results are as expected

    :param simulation_data: simulation_data of system_model
    :return:
    """
    expected_final_state = np.array([-1.04204510e-02, -3.01820367e-02,  7.50406978e-03,  1.09821509e-03,
       -2.17322620e-02,  2.13222039e-03, -3.09367996e-03, -1.08623196e-02,
        5.07750347e-04, -9.88255896e-04, -9.95200221e-04, -5.18756220e-03,
       -7.38736468e-03, -7.53517609e-03,  1.27142426e-02,  3.57141693e-03,
        1.15198772e-02, -1.42006138e-02,  1.20077382e-02,  1.21709951e-02,
        1.94812540e-03, -1.71850153e-03,  5.19041221e-04, -2.45202476e-04,
       -3.10265445e-01, -2.84015897e-02,  1.13835626e-02,  1.62711807e-01,
       -1.08268988e-01,  2.29079983e-02, -7.56664313e-02, -1.18739717e-01,
        5.79852794e-03, -4.20124668e-02,  1.36141250e-01, -9.00868123e-02,
       -9.07558931e-04,  1.75544200e-01,  1.58722750e-01,  1.25106901e-01,
       -1.04055266e-01,  1.59161199e-01, -9.17062017e-02,  1.29125538e-01,
        2.58137806e-02, -1.12375303e-02,  1.51851910e-02, -2.71152835e-03])

    rc = ResultContainer(score=1.0)
    simulated_final_state = simulation_data.y[:, -1]
    rc.final_state_errors = [
        simulated_final_state[i] - expected_final_state[i] for i in np.arange(0, len(simulated_final_state))
    ]
    rc.success = np.allclose(expected_final_state, simulated_final_state, rtol=0, atol=1e-2)

    return rc